### ISSUE TITLE
Update site doesn't work

### ISSUE THREAD

**Issue by piyenghar** [dice-project/DICE-Profiles#1] opened 2016-03-03 12:48 UTC
Hello,

It seems the update-website has an issue and eclipse is unable to pull up the update site. Could you please look into it..

Best regards

**Comment by abelgomez** [comment] 2016-03-03 23:36
Hi @piyenghar ,

could you be so kind to define "issue"? I (and other people too) have installed the plugins from the update site several times, in different days, and the update site worked as expected.

Best regards,

Abel

**Comment by piyenghar** [comment] 2016-03-04 08:16
Hi

Sorry about the post. We tried after sometime and a few attempts, it seems to work. But initially it gives us a message that eclipse update "cannot perform operations and its computing alternate solutions, so it may take a while 5/15".

Best regards
Padma

**Comment by abelgomez** [comment] 2016-03-04 12:09
Hi @piyenghar ,

the DAM profile requires Papyrus 1.1.x and the MARTE profile. That's why you may receive the "computing alternate solutions" message.

Since you have confirmed that the Update Site is ok, I'll close the issue.

**Closed as completed by abelgomez** 2016-03-04 12:09 UTC
